### ISSUE TITLE
Anki 23.20.1 下插件不工作了

### ISSUE THREAD

**Issue by lumeng** [qiyu/anki_moji#11]
求更新 :)

**Comment by qiyu** [comment]
好的，我这周末处理一下

**Comment by adanddyeah** [comment]
同。辛苦大佬了。

Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-12.7.1-x86_64-i386-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-24 21:05:49

When loading MojiToAnkimojidictcom:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "/Users/zhenshenghe/Library/Application Support/Anki2/addons21/131403862/__init__.py", line 1, in <module>
    from PyQt5.QtWidgets import QAction
ModuleNotFoundError: No module named 'PyQt5'
