### ISSUE TITLE
导入报错

### ISSUE THREAD

**Issue by icylian** [qiyu/anki_moji#7]
如题，升级插件到最新版本后是，从moji导入功能报错，旧版本可以正常导入，报错日志如下：

错误
发生了一个错误。请在启动Anki时按住「Shift」键临时禁用插件加载。 如仅在插件启用时出错，请使用「工具」>「插件」功能禁用部分插件后重启Anki， 请重复上述步骤直至找到引起错误的插件。 找到引起错误的插件后，请反馈给插件作者。 调试信息：
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-01-13 01:17:56

Caught exception:
Traceback (most recent call last):
  File "C:\Users\***\AppData\Roaming\Anki2\addons21\131403862\core\gui.py", line 189, in run
    self.save_words()
  File "C:\Users\***\AppData\Roaming\Anki2\addons21\131403862\core\gui.py", line 214, in save_words
    for duplicate, r in self.moji_server.fetch_all_from_server(
  File "C:\Users\***\AppData\Roaming\Anki2\addons21\131403862\core\mojidict_server.py", line 362, in fetch_all_from_server
    mojiwords = self.parse_rows(unique_rows, moji_folder)
  File "C:\Users\***\AppData\Roaming\Anki2\addons21\131403862\core\mojidict_server.py", line 162, in parse_rows
    raise e
  File "C:\Users\***\AppData\Roaming\Anki2\addons21\131403862\core\mojidict_server.py", line 135, in parse_rows
    example['trans'],
KeyError: 'trans'

**Comment by qiyu** [comment]
新版本增加了对收藏夹里的句子的抓取。从日志看，应该是某个收藏的句子缺少翻译信息引起的。你能找到引起问题的句子是哪个吗？如果能找到，麻烦提供下moji web的链接。

**Comment by qiyu** [comment]
可以按下面这个教程打开Console，然后执行上述用例，这样可以获取更详细的信息
https://addon-docs.ankiweb.net/console-output.html#windows

**Comment by icylian** [comment]
Console输出（日语乱码了）：
HTTPSConnectionPool(host='ankiweb.net', port=443): Max retries exceeded with url: /shared/updates/131403862?v=3 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
JS error /_anki/legacyPageData?id=2068346783920:1 Uncaught TypeError: Cannot read properties of null (reading 'offsetHeight')
2023-01-13 15:02:46 anki_moji 澶勭悊鏁版嵁鍑洪敊锛歿"createdBy": "KXXzHAKc7c", "updatedBy": "KXXzHAKc7c", "appId": "com.mojitec.mojidict", "langEnv": "zh-CN_ja", "targetId": "220120e8952", "targetType": 103, "title": "鈥︺伀涓€绺枫伄鏈涖伩銈掋亱銇戙倠銆?, "parentFolderId": "1utvBYXw5u", "targetUserId": "moji", "targetIsShared": false, "tmp": 0, "isChecked": false, "createdAt": "2022-10-10T15:04:43.585Z", "updatedAt": "2022-10-10T15:04:43.585Z", "objectId": "FgMd2Yk6yf", "target": {"title": "鈥︺伀涓€绺枫伄鏈涖伩銈掋亱銇戙倠銆?, "wordId": "220120w14210", "subdetailsId": "220120s19192", "quality": 1000, "isChecked": false, "objectId": "220120e8952"}}

根据Console输出找到的缺少翻译的词组链接：
https://www.mojidict.com/details/220120w14210

**Comment by qiyu** [comment]
引起问题的是这个例句，这个例句缺少了翻译信息
https://www.mojidict.com/example/220120e8952

后续会修复这个问题。在修复之前，你可以先将这个例句移到别的文件夹下。

**Comment by icylian** [comment]
好的，赞美大佬

**Comment by qiyu** [comment]
已修复
